import type { Metadata } from "next"
import { Inter, Montserrat } from "next/font/google"
import "./globals.css"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

const montserrat = Montserrat({
  subsets: ['latin'],
  weight: ['400', '700']
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="pt-br">
      <head>
        <title>Clima Agora</title>
      </head>
      <body className={`h-screen dark:bg-dark dark:text-dark-txt
        transition-colors duration-300
      `}>
        {children}
      </body>
    </html>
  )
}
